### ISSUE TITLE
Can I use the "Button" in "Toggle" by "as"?

### ISSUE THREAD

**Issue by AuTa** [stefan-karger/solid-ui#151]
I want to set the button in **Toggle** to be a **Button** component so I can use `variant="ghost"`. However, when I use `as={Button}` in **Toggle**, the `variant` is of the Toggle's type, and I can't select `ghost`. Currently, I can only use `as={Button}` within **TooltipTrigger**, but this results in a nested button. 

Is there a way to enable Toggle to directly use the types from the Button component? Thank you.

**Comment by stefan-karger** [comment]
You need to type it as `as={Button<"button">}`.
Unfortunatelly typescript can't fetch the type orrectly otherwise.

**Comment by AuTa** [comment]
Yeah, the two kinds of button used same `variant` and `size`, but the style is different.

Now, I type it `as="div"`, this is work well.
