### ISSUE TITLE
The height of Combobox is inconsistent with the height of TextField

### ISSUE THREAD

**Issue by AuTa** [stefan-karger/solid-ui#154]
Because the border of Combobox is added to the outer `div` and the height of `h-10` is defined on the inner `input`, the height of Combobox is two more borders than that of TextField.

Maybe defined as `h-10` on the outer `div`, so that the border blends into the height.

<img width="308" alt="Snipaste_2024-12-12_18-51-29" src="https://github.com/user-attachments/assets/2e4955c9-da1f-4d89-84b0-40241fa23761" />
<img width="241" alt="Snipaste_2024-12-12_18-52-10" src="https://github.com/user-attachments/assets/169aa39a-4250-4ea9-aa9d-d59e423ac892" />

**Comment by stefan-karger** [comment]
Thanks for catching that issue :)
Fixed and deployed!
